apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-frontend
  namespace: default
  labels:
    team: pensjonselvbetjening
spec:
  image: {{ image_sbs }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 3
    timeout: 1
  ingresses:
    - "https://pensjon-selvbetjening-opptjening-frontend.nais.oera.no"
    - "https://www.nav.no/pensjon/opptjening"
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 3
    timeout: 1
  vault:
    enabled: true
    paths:
      - kvPath: "apikey/apigw/prod/pensjon-selvbetjening-opptjening-backend/pensjon-selvbetjening-opptjening-frontend_p"
        mountPath: "/secret/apigw"
  env:
    - name: "API_GATEWAY"
      value: "https://api-gw.oera.no/pensjon-selvbetjening-opptjening-backend"
