apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-frontend
  namespace: default
  labels:
    team: pensjonselvbetjening
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 3
    timeout: 1
  ingresses:
    - "https://pensjon-selvbetjening-opptjening-frontend.nais.preprod.local"
    - "https://pensjon-selvbetjening-opptjening-frontend.dev-sbs.nais.io"
    - "https://www-q0.nav.no/pensjon/opptjening"
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 3
    timeout: 1
  vault:
    enabled: true
    paths:
      - kvPath: "apikey/apigw/dev/pensjon-selvbetjening-opptjening-backend/pensjon-selvbetjening-opptjening-frontend_q1"
        mountPath: "/secret/apigw"
  env:
    - name: "API_GATEWAY"
      value: "https://api-gw-q1.oera.no/pensjon-selvbetjening-opptjening-backend"
    - name: "REACT_APP_LOGINSERVICE_URL"
      value: "https://loginservice-q.nav.no/login?redirect=https://www-q0.nav.no/pensjon/opptjening/"
    - name: "REACT_APP_DECORATOR_URL"
      value: "https://www-q1.nav.no/dekoratoren"
