apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-frontend
  namespace: default
  labels:
    team: pensjonselvbetjening
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 3
    timeout: 1
  ingresses:
    - "https://pensjon-selvbetjening-opptjening-frontend.nais.preprod.local/"
    - "https://pensjon-selvbetjening-opptjening-frontend.dev-sbs.nais.io/"
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 3
    timeout: 1
  vault:
    enabled: true
