name: NAIS Deploy to prod-sbs

on:
  push:
    branches:
      - master

jobs:
  deploy-to-prod:
    name: Deploy to prod-sbs
    runs-on: ubuntu-latest
    env:
      IMAGE_SBS: docker.pkg.github.com/${{ github.repository }}/pensjon-selvbetjening-opptjening-frontend-prod:${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Build application
        env:
          REACT_APP_LOGINSERVICE_URL: "https://loginservice.nav.no/login?redirect="
          REACT_APP_DECORATOR_URL: "https://www.nav.no/dekoratoren"
          REACT_APP_DINPENSJON_URL: "https://tjenester.nav.no/pselv/publisering/dinpensjon.jsf"
          REACT_APP_DINEPENSJONSPOENG_URL: "https://tjenester.nav.no/pselv/publisering/dinepensjonspoeng.jsf"
          REACT_APP_PENSJONSKALKULATOR_URL: "https://tjenester.nav.no/pselv/simulering.jsf"
          REACT_APP_OVERFORE_OMSORGSOPPTJENING_URL: "https://tjenester.nav.no/pselv/publisering/overforeomsorgspoeng.jsf"
        run: npm run build
      - name: Build Docker image SBS
        run: |
          docker build -f Dockerfile-sbs -t ${IMAGE_SBS} .
      - name: Login to Github Package Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$GITHUB_REPOSITORY" --password-stdin docker.pkg.github.com
      - name: Push Docker image SBS
        run: "docker push ${IMAGE_SBS}"
      - name: Generate NAIS variables SBS
        run: |
          cat > nais/vars-sbs.yaml <<EOF
          namespace: default
          image_sbs: $IMAGE_SBS
          EOF
      - name: Deploy to prod-sbs
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-sbs
          RESOURCE: nais/nais-prod-sbs.yml
          VARS: nais/vars-sbs.yaml
