name: NAIS Deploy to dev-sbs

on: workflow_dispatch

jobs:
  deploy-to-dev:
    name: Deploy to dev-sbs
    runs-on: ubuntu-latest
    env:
      IMAGE_DEV_SBS: ghcr.io/${{ github.repository }}/pensjon-selvbetjening-opptjening-frontend-dev-sbs:${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Build application
        env:
          REACT_APP_LOGINSERVICE_URL: "https://loginservice.dev.nav.no/login?redirect="
          REACT_APP_OPPTJENING_ENDPOINT: "/api/opptjening"
          REACT_APP_DECORATOR_URL: "https://dekoratoren.dev.nav.no"
          REACT_APP_DINPENSJON_URL: "https://pensjon-pselv-q2.dev.nav.no/pselv/publisering/dinpensjon.jsf"
          REACT_APP_DINEPENSJONSPOENG_URL: "https://pensjon-pselv-q2.dev.nav.no/pselv/publisering/dinepensjonspoeng.jsf"
          REACT_APP_PENSJONSKALKULATOR_URL: "https://pensjon-pselv-q2.dev.nav.no/pselv/simulering.jsf"
          REACT_APP_OVERFORE_OMSORGSOPPTJENING_URL: "https://pensjon-pselv-q2.dev.nav.no/pselv/publisering/overforeomsorgspoeng.jsf"
        run: npm run build
      - name: Build Docker image dev-sbs
        run: |
          docker build -f Dockerfile-sbs -t ${IMAGE_DEV_SBS} .
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-sbs
          push: true
          tags: ${{ env.IMAGE_DEV_SBS }}
      - name: Generate NAIS variables dev-sbs
        run: |
          cat > nais/vars-dev-sbs.yaml <<EOF
          namespace: default
          image_dev_sbs: $IMAGE_DEV_SBS
          EOF
      - name: Deploy to dev-sbs
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: nais/nais-dev-sbs.yml
          VARS: nais/vars-dev-sbs.yaml
