name: NAIS Deploy to dev-gcp

on: workflow_dispatch

jobs:
  deploy-to-dev:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    env:
      IMAGE_DEV_GCP: docker.pkg.github.com/${{ github.repository }}/pensjon-selvbetjening-opptjening-frontend-dev-gcp:${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Build application
        env:
          REACT_APP_LOGINSERVICE_URL: "https://loginservice.dev.nav.no/login?redirect="
          REACT_APP_OPPTJENING_ENDPOINT: "/api/opptjening"
          REACT_APP_DECORATOR_URL: "https://dekoratoren.dev.nav.no"
          REACT_APP_DINPENSJON_URL: "https://pensjon-pselv-q2.dev.nav.no/pselv/publisering/dinpensjon.jsf"
          REACT_APP_DINEPENSJONSPOENG_URL: "https://pensjon-pselv-q2.dev.nav.no/pselv/publisering/dinepensjonspoeng.jsf"
          REACT_APP_PENSJONSKALKULATOR_URL: "https://pensjon-pselv-q2.dev.nav.no/pselv/simulering.jsf"
          REACT_APP_OVERFORE_OMSORGSOPPTJENING_URL: "https://pensjon-pselv-q2.dev.nav.no/pselv/publisering/overforeomsorgspoeng.jsf"
        run: npm run build
      - name: Build Docker image dev-gcp
        run: |
          docker build -f Dockerfile-gcp -t ${IMAGE_DEV_GCP} .
      - name: Login to Github Package Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$GITHUB_REPOSITORY" --password-stdin docker.pkg.github.com
      - name: Push Docker image dev-gcp
        run: "docker push ${IMAGE_DEV_GCP}"
      - name: Generate NAIS variables dev-gcp
        run: |
          cat > nais/vars-dev-gcp.yaml <<EOF
          namespace: default
          image_dev_gcp: $IMAGE_DEV_GCP
          EOF
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/nais-dev-gcp.yml
          VARS: nais/vars-dev-gcp.yaml
