name: NAIS Deploy

on:
  push:
    branches:
      - master

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/pensjon-selvbetjening-opptjening-frontend:${{ github.sha }}

jobs:
  deploy-to-dev:
    name: Deploy to dev-sbs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Build Docker image
        run: |
          docker build -t ${IMAGE} .
      - name: Login to Github Package Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$GITHUB_REPOSITORY" --password-stdin docker.pkg.github.com
      - name: Push Docker image
        run: "docker push ${IMAGE}"
      - name: Deploy to dev-sbs
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: nais/nais-dev.yml
