name: NAIS Deploy to dev-fss

on:
  push:
    branches:
      - master

jobs:
  deploy-to-dev:
    name: Deploy to dev-fss
    runs-on: ubuntu-latest
    env:
      IMAGE_DEV_FSS: docker.pkg.github.com/${{ github.repository }}/pensjon-selvbetjening-opptjening-frontend-dev-fss:${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Build application
        env:
          REACT_APP_LOGINSERVICE_URL: "https://pensjon-selvbetjening-opptjening-frontend.dev.adeo.no/pensjon/opptjening/oauth2/internal/login?redirect="
          REACT_APP_OPPTJENING_ENDPOINT: "/api/opptjeningonbehalf"
          REACT_APP_DECORATOR_URL: "https://www-q1.nav.no/dekoratoren"
          REACT_APP_DINPENSJON_URL: "https://pensjon-pselv-q2.dev.adeo.no/pselv/publisering/dinpensjon.jsf"
          REACT_APP_DINEPENSJONSPOENG_URL: "https://pensjon-pselv-q2.dev.adeo.no/pselv/publisering/dinepensjonspoeng.jsf"
          REACT_APP_PENSJONSKALKULATOR_URL: "https://pensjon-pselv-q2.dev.adeo.no/pselv/simulering.jsf"
          REACT_APP_OVERFORE_OMSORGSOPPTJENING_URL: "https://pensjon-pselv-q2.dev.adeo.no/pselv/publisering/overforeomsorgspoeng.jsf"
        run: npm run build
      - name: Build Docker image dev-fss
        run: |
          docker build -f Dockerfile-fss -t ${IMAGE_DEV_FSS} .
      - name: Login to Github Package Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$GITHUB_REPOSITORY" --password-stdin docker.pkg.github.com
      - name: Push Docker image dev-fss
        run: "docker push ${IMAGE_DEV_FSS}"
      - name: Generate NAIS variables dev-fss
        run: |
          cat > nais/vars-dev-fss.yaml <<EOF
          namespace: default
          image_dev_fss: $IMAGE_DEV_FSS
          EOF
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/nais-dev-fss.yml
          VARS: nais/vars-dev-fss.yaml
