name: Test code

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          npm ci
          npx cypress verify
          npx cypress info
          npx cypress version
          npx cypress version --component package
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Run build
        run: npm run build
      - name: Cypress run with express.js
        run: npm run test:cycli
        env:
          HOST: "172.17.0.1" #172.17.0.1 = docker.internal.host on linux